local util = require("opencode.util")

describe("util.merge", function()
  it("merges nested tables with later arguments winning", function()
    local out = util.merge({ a = { x = 1, y = 2 } }, { a = { y = 3 } })
    assert.are.equal(1, out.a.x)
    assert.are.equal(3, out.a.y)
  end)
end)

describe("util.join", function()
  it("joins components with a slash", function()
    assert.are.equal("a/b/c", util.join("a", "b", "c"))
  end)
end)

describe("util.find_up", function()
  it("returns the first match walking upward", function()
    local dir = vim.fn.tempname()
    vim.fn.mkdir(dir .. "/a/b", "p")
    vim.fn.writefile({ "x" }, dir .. "/marker")
    assert.are.equal(dir .. "/marker", util.find_up("marker", dir .. "/a/b"))
    vim.fn.delete(dir, "rf")
  end)

  it("returns nil when nothing matches", function()
    local dir = vim.fn.tempname()
    vim.fn.mkdir(dir, "p")
    assert.is_nil(util.find_up("does-not-exist-anywhere", dir))
    vim.fn.delete(dir, "rf")
  end)
end)

describe("util.read_json", function()
  it("returns nil for a missing file", function()
    assert.is_nil(util.read_json("/definitely/not/here.json"))
  end)

  it("returns nil for invalid JSON", function()
    local path = vim.fn.tempname()
    vim.fn.writefile({ "not json" }, path)
    assert.is_nil(util.read_json(path))
    vim.fn.delete(path)
  end)

  it("parses a JSON object", function()
    local path = vim.fn.tempname()
    vim.fn.writefile({ '{"a":1,"b":["x"]}' }, path)
    assert.are.same({ a = 1, b = { "x" } }, util.read_json(path))
    vim.fn.delete(path)
  end)
end)
